config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, shallow: true do
    get '/setup', to: 'recorders#new'
    post '/setup', to: 'recorders#create'
    resources :recorders, except: [:new, :create], shallow: true do
      resources :options, except: [:show, :new, :create], shallow: true do
        resources :records, only: [:create, :destroy]
      end
      resources :recordabilities, except: [:index, :show]
    end
  end
  get 'recorders/:id/add_options', to: 'recorders#add_options', as: :recorder_add_options
  patch 'recorders/:id/add_options', to: 'recorders#update_options'
  get 'recorders/:id/edit_title', to: 'recorders#edit_title', as: :recorder_edit_title
  patch 'recorders/:id/edit_title', to: 'recorders#update_title'
  get 'recorders/:id/delete', to: 'recorders#delete', as: :delete_recorder
  get 'recorders/:id/graph', to: 'graph#show', as: :graph
  post 'options/:id/register', to: 'single_register#create', as: :single_register
  get 'options/:id/delete', to: 'options#delete', as: :delete_option
  get 'recordabilities/:id/duplicate', to: 'recordabilities#duplicate', as: :duplicate_recordability
  get 'recordabilities/:id/delete', to: 'recordabilities#delete', as: :delete_recordability
  get '/delete_recordablities', to: 'plural_actions#delete_recordabilities', as: :delete_recordabilities
  delete '/delete_recordablities', to: 'plural_actions#destroy_recordabilities'
  get '/delete_options', to: 'plural_actions#delete_options', as: :delete_options
  delete '/delete_options', to: 'plural_actions#destroy_options'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  This is the help page for the Counter.
<p>

app/views/static_pages/home.html.erb
<div class="container">
  <h1>ようこそ!</h1>
  <p>こちらは選択肢を選んで記録を追加するカウンターサイトです。記録に用いる選択肢は自分で作成できます。</p>
  <%= link_to "サインアップ", signup_path, class: "btn waves-effect waves-light" %>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col m4">
      <h2>カウンターの作成</h2>
      <p>記録をするためにまずカウンターを作成しましょう。作成したカウンターにお好きな選択肢を持たせれば準備完了です</p>
      <%= link_to "カウンター作成へ", user_setup_path(current_user), class: "btn waves-effect waves-light" if logged_in?%>
    </div>
    <div class="col m4">
      <h2>記録の追加</h2>
      <p>カウンターの一覧ページから記録を追加したいカウンターを選びましょう。選んだカウンターの選択肢一覧から記録に追加したい選択肢をクリックすると記録に追加されます．</p>
      <%= link_to "カウンターの一覧へ", user_recorders_path(current_user), class: "btn waves-effect waves-light" if logged_in?%>
    </div>
    <div class="col m4">
      <h2>以下のような方々に</h2>
      <ul>
        <li>勝負の勝ち負けのような数種類の内容を繰り返し記録したい</li>
        <li>記録した内容の出現率が知りたい</li>
      </ul>
    </div>
  </div>
</div>