config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, shallow: true do
    get '/setup', to: 'recorders#new'
    post '/setup', to: 'recorders#create'
    resources :recorders, except: [:new, :create], shallow: true do
      resources :options, except: [:show, :new, :create], shallow: true do
        resources :records, only: [:create, :destroy]
      end
      resources :recordabilities, except: [:index, :show]
    end
  end
  get 'recorders/:id/add_options', to: 'recorders#add_options', as: :recorder_add_options
  patch 'recorders/:id/add_options', to: 'recorders#update_options'
  get 'recorders/:id/edit_title', to: 'recorders#edit_title', as: :recorder_edit_title
  patch 'recorders/:id/edit_title', to: 'recorders#update_title'
  get 'recorders/:id/delete', to: 'recorders#delete', as: :delete_recorder
  get 'recorders/:id/graph', to: 'graph#show', as: :graph
  post 'options/:id/register', to: 'single_register#create', as: :single_register
  get 'options/:id/delete', to: 'options#delete', as: :delete_option
  get 'recordabilities/:id/duplicate', to: 'recordabilities#duplicate', as: :duplicate_recordability
  get 'recordabilities/:id/delete', to: 'recordabilities#delete', as: :delete_recordability
  get '/delete_recordablities', to: 'plural_actions#delete_recordabilities', as: :delete_recordabilities
  delete '/delete_recordablities', to: 'plural_actions#destroy_recordabilities'
  get '/delete_options', to: 'plural_actions#delete_options', as: :delete_options
  delete '/delete_options', to: 'plural_actions#destroy_options'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :recorder, inverse_of: :options
  has_many :records, dependent: :destroy
  default_scope -> { order(:created_at) }
  validates :name, presence: true,
                   length: { maximum: 40 },
                   uniqueness: { scope: [:recorder_id] }
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  include RecorderFamily
  before_action :logged_in_user, except: [:edit, :update, :delete, :destroy]
  before_action -> {
    logged_in_user(recorder_options_url(parent_recorder))
  }, only: [:edit, :update, :delete, :destroy]
  before_action -> {
    correct_user(parent_user.id)
  }, only: [:index, :create, :new]
  before_action -> {
    correct_user(grand_parent_user.id)
  }, only: [:destroy, :edit, :update]

  def index
    @options = @recorder.options
  end

  def edit
    get_modal_window
  end

  def update
    if @option.update_attributes(single_option_params)
      flash[:success] = "選択肢を#{@option.name}に変更しました"
      update_recorder
    end
    @options = @recorder.options
    hide_modal_window @option, 'option', "#option-#{@option.id}",
                                         option: @option
  end

  def delete
    get_modal_window
  end

  def destroy
    name = @option.name
    @option.destroy
    delete_empty_recordabilities
    update_recorder
    flash[:success] = "選択肢#{name}を削除しました"
    @options = @recorder.options
    hide_modal_window @option,
                      "options/options_table",
                      ".options_table"
  end

  private

    def option_params
      strong = params.require(:recorder).permit(:title, options_attributes: [:id, :name, :recorder_id, :_destroy])
      strong[:options_attributes] = strong[:options_attributes].select {|n, options_attribute| !options_attribute[:name].blank?}
      return strong
    end

    def single_option_params
      params.require(:option).permit(:name)
    end

    def parent_user
      @recorder = Recorder.find(params[:recorder_id])
      @user = @recorder.user
    end

    def grand_parent_user
      @user = parent_recorder.user
    end

    def parent_recorder
      @option = Option.find(params[:id])
      @recorder = @option.recorder
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/views/options/_delete.html.erb
<%= render "shared/delete_form", name: "選択肢",
                                 body: "delete_confirmation",
                                 url: option_path(@option) %>

app/views/options/_delete_confirmation.html.erb
<div><%= @option.name %>を完全に削除しますか?</div>

app/views/options/_edit.html.erb
<% provide(:title, 'Edit option')%>
<% provide(:submit_url, option_path(@option)) %>
<% provide(:submit_text, '変更') %>

<%= render "shared/modal_form_template",
           heading: "選択肢: #{@option.name}を変更",
           html: 'edit_form' %>

app/views/options/_edit_form.html.erb
<%= form_for(@option, url: yield(:submit_url), remote: true) do |f| %>
  <div class="error_messages">
    <%= render 'shared/error_messages', object: f.object %>
  </div>

  <div class="field">
    <%= f.label :name, '新しい名前' %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= render "shared/modal_form_buttons", f: f %>
<% end %>

app/views/options/_option.html.erb
<span><%= check_box_tag 'ids[]', option.id %></span>
<div class="dropdown">
  <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">
    <span class="caret" aria-hidden="true"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "編集", edit_option_path(option), remote: true %></li>
    <li><%= link_to "削除", delete_option_path(option), remote: true %></li>
  </ul>
</div>
<h3>
  <%= option.name %>
</h3>

app/views/options/_options_table.html.erb
<% if @options.any? %>
  <%= form_tag({action: :delete_options, controller: :plural_actions } , { method: :get , remote: true}) do %>
    <div class="buttons-wrap">
      <div class="options-buttons">
        <%= link_to '追加',
                    recorder_add_options_path(@recorder),
                    class: "add_options_path btn btn-primary btn-sm",
                    remote: true %>
        <%= submit_tag "削除", class: "plural_action_button btn btn-danger btn-sm", disabled: true %>
        <%= button_tag "全選択", type: 'button', class: "check_all btn btn-default btn-sm" %>
        <span class="appear_checked"></span>
      </div>
    </div>

    <div class="options-list">
      <% @options.each do |option| %>
        <div id="option-<%= option.id %>">
          <%= render option %>
        </div>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>選択肢はありません</p>
  <p>
    <%= link_to '選択肢を追加',
                recorder_add_options_path(@recorder),
                class: "add_options_path",
                remote: true %>
  </p>
<% end %>

app/views/options/edit.html.erb
<% provide(:title, 'Edit option')%>
<% provide(:submit_url, option_path(@option)) %>
<% provide(:button_text, 'Save changes') %>
<h1>Update <%= @option.name %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'edit_form' %>
  </div>
</div>

app/views/options/index.html.erb
<% provide(:title, 'Edit options') %>
<h1>Edit title</h1>

<div class="row">
  <div class="col-md-2"><%= link_to "add options", recorder_add_options_path(@recorder), class: "btn btn-success" %>
</div>

<div class="btn-group btn-group-xs">
  <button type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "add options", recorder_add_options_path(@recorder) %></li>
  </ul>
</div>

<ul class="recorders">
    <%= render 'options_table' %>
</ul>
<div><%= link_to @recorder.title, recorder_path(@recorder) %>
<div class="modal fade modal-container"></div>