config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, shallow: true do
    get '/setup', to: 'recorders#new'
    post '/setup', to: 'recorders#create'
    resources :recorders, except: [:new, :create], shallow: true do
      resources :options, except: [:show, :new, :create], shallow: true do
        resources :records, only: [:create, :destroy]
      end
      resources :recordabilities, except: [:index, :show]
    end
  end
  get 'recorders/:id/add_options', to: 'recorders#add_options', as: :recorder_add_options
  patch 'recorders/:id/add_options', to: 'recorders#update_options'
  get 'recorders/:id/edit_title', to: 'recorders#edit_title', as: :recorder_edit_title
  patch 'recorders/:id/edit_title', to: 'recorders#update_title'
  get 'recorders/:id/delete', to: 'recorders#delete', as: :delete_recorder
  get 'recorders/:id/graph', to: 'graph#show', as: :graph
  post 'options/:id/register', to: 'single_register#create', as: :single_register
  get 'options/:id/delete', to: 'options#delete', as: :delete_option
  get 'recordabilities/:id/duplicate', to: 'recordabilities#duplicate', as: :duplicate_recordability
  get 'recordabilities/:id/delete', to: 'recordabilities#delete', as: :delete_recordability
  get '/delete_recordablities', to: 'plural_actions#delete_recordabilities', as: :delete_recordabilities
  delete '/delete_recordablities', to: 'plural_actions#destroy_recordabilities'
  get '/delete_options', to: 'plural_actions#delete_options', as: :delete_options
  delete '/delete_options', to: 'plural_actions#destroy_options'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recorder.rb
class Recorder < ApplicationRecord
  belongs_to :user
  default_scope -> { order(updated_at: :desc) }
  has_many :options, dependent: :destroy, inverse_of: :recorder
  has_many :recordabilities, dependent: :destroy
  accepts_nested_attributes_for :options, allow_destroy: true, reject_if: :reject_option
  accepts_nested_attributes_for :recordabilities, allow_destroy: true
  validates :user_id, presence: true
  validates :title, presence: true,
            length: { maximum: 255 }
            #uniqueness: { case_sensitive: false }

  def no_input_error
    errors[:base] << "何も入力されていません"
  end

  def reject_option(attr)
    attr[:name].blank?
  end
end

app/controllers/recorders_controller.rb
class RecordersController < ApplicationController
  include RecorderFamily
  before_action :logged_in_user, except: [:edit_title, :update_title, :add_options, :update_options, :delete, :destroy]
  before_action -> {
    logged_in_user(user_recorders_url(parent_user_id))
  }, only: [:delete, :destroy]
  before_action -> {
    logged_in_user(edit_recorder_url(Recorder.find(params[:id])))
  }, only: [:edit_title, :update_title, :add_options, :update_options]
  before_action -> {
    correct_user(parent_user_id)
  }, only: [:show, :add_options, :edit_title, :update_title, :edit, :update, :update_options, :delete, :destroy]
  before_action -> {
    correct_user(params[:user_id])
  }, only: [:index, :create, :new]

  def new
    @recorder = @user.recorders.build
    @recorder.options.build
  end

  def show
    @recordabilities = @recorder.recordabilities.all
    @recordability = @recorder.recordabilities.build
    @recorder.options.count.times do
      @recordability.records.build
    end
  end

  def create
    @recorder = @user.recorders.build(recorder_params)
    if @recorder.save
      flash[:success] = "カウンター#{@recorder.title}が作成されました"
      redirect_to @recorder
    else
      render 'new'
    end
  end

  def edit
    @options = @recorder.options
  end

  def update
    if @recorder.update_attributes(recorder_params)
      flash[:success] = "#{@recorder.title} successfully updated!"
      redirect_to @recorder
    else
      render 'recorders/edit'
    end
  end

  def edit_title
    get_modal_window
  end

  def update_title
    if @recorder.update_attributes(recorder_title)
      flash[:success] = "カウンター名を #{@recorder.title}に変更しました"
    end
    @recorders = @user.recorders.paginate(page: params[:page])
    hide_modal_window @recorder,
                      "recorder_title",
                      ".recorder-#{@recorder.id}_title",
                      recorder: @recorder
  end

  def add_options
    @recorder.options.build
    get_modal_window
  end

  def update_options
    if option_blank_all? recorder_params[:options_attributes]
      @recorder.no_input_error
    elsif
      before_count = @recorder.options.count
      @recorder.update_attributes(recorder_params)
      after_count = @recorder.options.count
      flash[:success] = "#{after_count - before_count}個の選択肢を追加しました"
      update_recorder
    end
    @options = @recorder.options
    if from_edit?
      hide_modal_window @recorder,
                        "options/options_table",
                        ".options_table"
    elsif from_show?
      hide_modal_window @recorder,
                        "shared/record_form",
                        ".record_form"
    else
      redirect_to(:back)
    end
  end

  def index
    @recorders = @user.recorders.paginate(page: params[:page])
  end

  def delete
    get_modal_window
  end

  def destroy
    @recorder.destroy
    @recorders = @user.recorders.paginate(page: params[:page])
    flash[:success] = "1つのカウンターが削除されました"
    redirect_to user_recorders_url(@user)
  end

  private

    def recorder_title
      params.require(:recorder).permit(:title)
    end

    def recorder_params
      params.require(:recorder).permit(:title, options_attributes: [:id, :name, :recorder_id, :_destroy])
    end

    def recorder_title
      params.require(:recorder).permit(:title)
    end

    def parent_user_id
      @recorder = Recorder.find(params[:id])
      @recorder.user_id
    end

    def before_actions
      Rails.application.routes.recognize_path(request.referrer)
    end

    def from_show?
      before_actions[:controller] == "recorders" && before_actions[:action] == "show"
    end

    def from_edit?
      before_actions[:controller] == "recorders" && before_actions[:action] == "edit"
    end

    def option_blank_all?(options_attributes)
      options_attributes.each { |index, attr| return false unless attr[:name].blank? }
      return true
    end
end

app/helpers/recorders_helper.rb
module RecordersHelper
end

app/views/recorders/_add_options.html.erb
<% provide(:submit_url, recorder_add_options_path(@recorder)) %>
<% provide(:submit_text, '追加') %>

<%= render "shared/modal_form_template",
           heading: "選択肢を追加",
           html: 'add_options_form' %>

app/views/recorders/_count_buttons.html.erb
<div class="operator">
  <div class="waves-effect waves-green side-btn decrement">
    <i class="material-icons">keyboard_arrow_left</i>
  </div>
  <div class="count"></div>
  <div class="waves-effect waves-green side-btn increment">
    <i class="material-icons">keyboard_arrow_right</i>
  </div>
</div>
<div class="name">
  <%= option.name %>
</div>

app/views/recorders/_delete.html.erb
<%= render "shared/delete_form", name: @recorder.title,
                                 body: "delete_confirmation",
                                 url: recorder_path(@recorder) %>

app/views/recorders/_delete_confirmation.html.erb
<div><%= @recorder.title %>を完全に削除しますか?</div>

app/views/recorders/_edit_title.html.erb
<% provide(:title, 'Edit counter')%>
<% provide(:submit_url, recorder_edit_title_path(@recorder)) %>
<% provide(:submit_text, '変更') %>

<%= render "shared/modal_form_template",
           heading: "カウンター名: #{@recorder.title}を変更",
           html: 'title_form' %>

app/views/recorders/_form.html.erb
<%= form_for(@recorder, url: yield(:submit_url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.label :title, "カウンター名" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <hr>

  <div class="form-group">
    <label>選択肢</label>
    <div id="options" class="scroll-window">
    <%= f.fields_for :options do |option_form| %>
      <%= render 'option_fields', f: option_form %>
    <% end %>
    </div>
  </div>
  <div class="actions">
    <div class="pull-left">
    <%= link_to_add_association "フォームを追加", f, :options,
                                                  class: "btn btn-default",
                                                  data: {
                                                  association_insertion_node: '#options',
                                                  association_insertion_method: 'append' } %>
    </div>
    <div class="pull-right">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/recorders/_options.html.erb
<div class="windowful">
  <div class="panel panel-default option-bar">
    <div class="option-bar-head">
      <div class="panel-heading side-item">
        <span class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">
            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "選択肢を追加", recorder_add_options_path(@recorder), remote: true %></li>
            <li><%= link_to "まとめて記録", new_recorder_recordability_path(@recorder), remote: true %></li>
          </ul>
        </span>
        選択肢
      </div>
    </div>
    <ul class="nav nav-pills nav-stacked">
      <section class="record_form">
        <%= render 'shared/record_form' %>
      </section>
    </ul>
  </div>
</div>

app/views/recorders/_options_form.html.erb
<%= form_for(@recorder, url: recorder_recordabilities_path(@recorder),
  method: :post, remote: true) do |f| %>
  <%= f.fields_for @recordability do |fr| %>
    <div class="modal-content">
      <div class="modal-close modal-close-icon"><i class="material-icons toolbar-icon">close</i></div>
      <ul class="owl-carousel owl-theme modal-main">
        <% @recorder.options.zip(new_fields_for(fr, :records)).each_slice(6).with_index do |items, i| %>
          <li>
            <%= render 'options_form_main', items: items, i: i %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="modal-footer">
      <%= f.submit recorder_recordabilities_path(@recorder), class: "modal-close waves-effect btn-flat" %>
    </div>
  <% end %>
<% end %>

app/views/recorders/_options_form_main.html.erb
<% items.each.with_index(i) do |(option, fr), j| %>
  <div class=<%= "form-option-#{j}" %>>
    <div class="input-field count-select">
      <%= fr.label :count, option.name, class: "label-xs" %>
      <%= render 'count_buttons', option: option %>
      <%= fr.hidden_field :count, value: 0 , class: "hidden-count" %>
      <%= fr.hidden_field :option_id, value: option.id %>
    </div>
  </div>
<% end %>

app/views/recorders/_recorder_title.html.erb
<p>
  <%= @recorder.title %>
  <%= link_to sanitize('<span class="glyphicon glyphicon-pencil" aria-hidden="true"</sapn>'),
              recorder_edit_title_path(@recorder),
              class: "edit_title_path",
              remote: true %>

</p>

app/views/recorders/_records_tbody.html.erb
<tbody class="records-tbody">
<% @recordabilities.each do |recordability, i| %>
  <% rowspan = recordability.records.count %>
    <% recordability.records.each.with_index(1) do |record, i| %>
      <tr id="record-<%= record.id %>">
        <% if i == 1 %>
          <td rowspan=<%= rowspan %> class="record-select"><%= check_box_tag 'ids[]', recordability.id %></td>
          <td rowspan=<%= rowspan %> class="record-action">
            <div class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">
                <span class="caret" aria-hidden="true"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "複製", duplicate_recordability_path(recordability) %></li>
                <li><%= link_to "編集", edit_recordability_path(recordability), remote: true %></li>
                <li><%= link_to "削除", delete_recordability_path(recordability), remote: true %></li>
              </ul>
            </div>
          </td>
          <td rowspan=<%= rowspan %> class="record-no"><%= recordability_index(recordability) %>.</td>
        <% end %>
        <td class="record-data">
          <div class="row">
            <%= record.option.name %>
          </div>
          <% if i == rowspan %>
            <div class="row timestamp">
              <%= time_ago_in_words(record.created_at) %>前
            </div>
          <% end %>
        </td>
        <td class="record-count"><%= record.count %></td>
        <% if i == 0 %>
        <% end %>
      </tr>
    <% end %>
<% end %>
</tbody>

app/views/recorders/_title_form.html.erb
<%= form_for(@recorder, url: yield(:submit_url), remote: true) do |f| %>
  <div class="error_messages">
    <%= render 'shared/error_messages', object: f.object %>
  </div>

  <div class="field">
    <%= f.label :title, "新しい名前" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <%= render "shared/modal_form_buttons", f: f %>
<% end %>

app/views/recorders/index.html.erb
<% provide(:title, 'カウンター一覧') %>
<h1>カウンターの一覧</h1>

<div class="setup-button"><%= link_to "新規作成", user_setup_path(@user), class: "btn btn-primary" %></div>

<div id="recorders_index" class="recorders">
  <%= render "recorders" %>
</div>


<div class="modal fade modal-container"></div>

app/views/recorders/show.html.erb
<% provide(:title, @recorder.title) %>

<div class="row">
  <div class="col-sm-3 options-col">
    <%= render "options" %>
    <div class="slide-button-container"></div>
  </div>
  <div class="col-sm-9 col-xs-12 records-table">
    <div class="row records-head">
      <div class="heading">
        <h2>
          <%= @recorder.title %>
        </h2>
        <div>
          <%= link_to sanitize('<i class="material-icons fab-icon">pie_chart</i>'),
                      graph_path(@recorder), class: "graph_path" %>
          <%= link_to sanitize('<i class="material-icons fab-icon">settings</i>'),
                      edit_recorder_path(@recorder) %>
        </div>
      </div>
    </div>
    <div class="row records-body">
      <%= render 'records_table' %>
    </div>
  </div>
</div>

<!--
<a class="btn-floating cover-activate">
  <i class="material-icons cover-activate-icon">add</i>button
</a>
-->

<!--
<div class="fab">
  <%= link_to "", new_recorder_recordability_path(@recorder),
    class: "fab-background ajax-cover-open fab-expand z-depth-2 hoverable", remote: true %>
  <i class="material-icons fab-icon">add</i>
</div>
-->

<div class="toolbar-container">
  <div class="container">
    <div class="row">
      <div class="toolbar-fixed z-depth-2">
      <ul>
        <li>
          <%= link_to sanitize('<i class="material-icons toolbar-icon">add</i>'),
                      "#modal-options-form", class: "modal-trigger waves-effect waves-light options-form-trigger" %>
        </li>
        <li class="waves-effect waves-light"><i class="material-icons toolbar-icon">edit</i></li>
        <li class="waves-effect waves-light"><i class="material-icons toolbar-icon">delete</i></li>
        <li class="waves-effect waves-light"><i class="material-icons toolbar-icon">check_all</i></li>
        <li class="waves-effect waves-light"><i class="material-icons toolbar-icon">clear_all</i></li>
      </ul>
      </div>
    </div>
  </div>
</div>

<div id="modal-options-form" class="modal">
  <%= render 'options_form' %>
</div>
<!--
<div class="cover-view"></div>
-->