config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, shallow: true do
    get '/setup', to: 'recorders#new'
    post '/setup', to: 'recorders#create'
    resources :recorders, except: [:new, :create], shallow: true do
      resources :options, except: [:show, :new, :create], shallow: true do
        resources :records, only: [:create, :destroy]
      end
      resources :recordabilities, except: [:index, :show]
    end
  end
  get 'recorders/:id/add_options', to: 'recorders#add_options', as: :recorder_add_options
  patch 'recorders/:id/add_options', to: 'recorders#update_options'
  get 'recorders/:id/edit_title', to: 'recorders#edit_title', as: :recorder_edit_title
  patch 'recorders/:id/edit_title', to: 'recorders#update_title'
  get 'recorders/:id/delete', to: 'recorders#delete', as: :delete_recorder
  get 'recorders/:id/graph', to: 'graph#show', as: :graph
  post 'options/:id/register', to: 'single_register#create', as: :single_register
  get 'options/:id/delete', to: 'options#delete', as: :delete_option
  get 'recordabilities/:id/duplicate', to: 'recordabilities#duplicate', as: :duplicate_recordability
  get 'recordabilities/:id/delete', to: 'recordabilities#delete', as: :delete_recordability
  get '/delete_recordablities', to: 'plural_actions#delete_recordabilities', as: :delete_recordabilities
  delete '/delete_recordablities', to: 'plural_actions#destroy_recordabilities'
  get '/delete_options', to: 'plural_actions#delete_options', as: :delete_options
  delete '/delete_options', to: 'plural_actions#destroy_options'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper" id="nav-header">
      <%= link_to "Counter", root_path, id: "logo", class: "brand-logo right" %>
      <a href="#" data-target="topside-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="left hide-on-med-and-down">
        <%= render 'layouts/nav_item' %>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="topside-nav">
    <%= render 'layouts/nav_item' %>
  </ul>
</header>

app/views/layouts/_nav_item.html.erb
<li><%= link_to "トップ", root_path %></li>
<% if logged_in? %>
  <% if current_user.admin? %>
    <li><%= link_to "Users", users_path %></li>
  <% end %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" role="button">
     カウンター<b class="caret"></b>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "一覧", user_recorders_path(current_user) %></li>
      <li class="devider"></li>
      <li><%= link_to "作成", user_setup_path(current_user) %></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" role="button">
     アカウント<b class="caret"></b>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "ユーザー情報の編集", edit_user_path(current_user) %></li>
      <li class="devider"></li>
      <li>
        <%= link_to "ログアウト", logout_path, method: "delete" %>
      </li>
    </ul>
  </li>
<% else %>
  <li><%= link_to "ログイン", login_path %></li>
<% end %>

app/views/layouts/_rails_default.html.erb
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body data-controller=<%= params[:controller] %> data-action=<%= params[:action] %>>
    <%= render 'layouts/header' %>
    <div id="flash_messages">
      <%= render "shared/flash_messages" %>
    </div>
    <%= yield %>
    <div id='loading'>
      <%= render "shared/loading.html.erb" %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>